apiVersion: v1
kind: Secret
metadata:
  name: myapp-secrets
  namespace: default
  labels:
    app: myapp
type: Opaque
stringData:
  database-url: "postgresql://user:password@db-host:5432/myapp"
  api-key: "your-api-key-here"
  jwt-secret: "your-jwt-secret-here"
---
apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: BASE64_ENCODED_DOCKER_CONFIG
# Create with: kubectl create secret docker-registry acr-secret \
#   --docker-server=myregistry.azurecr.io \
#   --docker-username=username \
#   --docker-password=password \
#   --docker-email=email@example.com
